
package com.elgin.cxf.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.elgin.cxf.service.impl.HelloServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-14T09:12:29.133+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class HelloService_HelloServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.cxf.elgin.com/", "HelloServiceImplService");

    private HelloService_HelloServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloServiceImplService ss = new HelloServiceImplService(wsdlURL, SERVICE_NAME);
        HelloService port = ss.getHelloServiceImplPort();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_text = "";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_text);
        System.out.println("sayHello.result=" + _sayHello__return);


        }
        {
        System.out.println("Invoking getUserByName...");
        java.lang.String _getUserByName_arg0 = "";
        com.elgin.cxf.service.User _getUserByName__return = port.getUserByName(_getUserByName_arg0);
        System.out.println("getUserByName.result=" + _getUserByName__return);


        }

        System.exit(0);
    }

}
