package com.elgin.cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-14T09:12:29.201+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.cxf.elgin.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.cxf.elgin.com/", className = "com.elgin.cxf.service.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.cxf.elgin.com/", className = "com.elgin.cxf.service.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://service.cxf.elgin.com/", className = "com.elgin.cxf.service.GetUserByName")
    @WebMethod
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://service.cxf.elgin.com/", className = "com.elgin.cxf.service.GetUserByNameResponse")
    public com.elgin.cxf.service.User getUserByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
